In [1]:
import pandas as pd
import numpy as np

In [2]:
test_run = pd.read_csv('data.csv')

In [3]:
test_run.describe()
print(test_run['chamber'].nunique())

480

In [4]:
print(test_run.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1920 entries, 0 to 1919
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   chamber             1920 non-null   object
 1   wheel               1920 non-null   int64
 2   sector              1920 non-null   int64
 3   station             1920 non-null   int64
 4   avg_cluster_size    1920 non-null   float64
 5   occupancy           1920 non-null   int64
 6   avg_bx_dist         1920 non-null   float64
 7   avg_no_of_clusters  1920 non-null   float64
 8   avg_multiplicity    1920 non-null   float64
 9   lumisections        1920 non-null   int64
 10  type                1920 non-null   object
 11  avg_efficiency      1920 non-null   float64
dtypes: float64(5), int64(5), object(2)
memory usage: 180.1+ KB
None

In [6]:
test_run.head(100)

,chamber,wheel,sector,station,avg_cluster_size,occupancy,avg_bx_dist,avg_no_of_clusters,avg_multiplicity,lumisections,type,avg_efficiency
0,W-2_RB1in_S01,-2,1,1,1.89560,9260,0.014739,1.00494,1.90496,131,Col,49.159065
1,W-2_RB1out_S01,-2,1,1,1.86138,8352,0.017384,1.00448,1.86971,131,Col,55.115120
2,W-2_RB2in_S01,-2,1,2,1.98668,9991,0.012328,1.00439,1.99541,131,Col,77.418091
3,W-2_RB2out_S01,-2,1,2,1.81836,8419,0.012527,1.00347,1.82466,131,Col,80.450953
4,W-2_RB3+_S01,-2,1,3,1.86244,4021,0.004632,1.00279,1.86763,131,Col,91.251781
...,...,...,...,...,...,...,...,...,...,...,...,...
95,W-2_RB4-_S12,-2,12,4,1.60847,2469,0.001954,1.00000,1.60847,131,Col,20.000000
96,W-1_RB1in_S01,-1,1,1,2.06804,15866,0.009515,1.00669,2.08188,131,Col,83.344437
97,W-1_RB1out_S01,-1,1,1,2.06215,14134,0.010651,1.00587,2.07426,131,Col,83.581627
98,W-1_RB2in_S01,-1,1,2,1.88589,12775,0.008562,1.00341,1.89231,131,Col,87.895691
99,W-1_RB2out_S01,-1,1,2,1.96977,11665,0.009794,1.00458,1.97880,131,Col,88.100712